theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jyo Pari

# Short bio or description (displayed in the header)
description: Interesting Explanations
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://img.itch.zone/aW1nLzMyMzM2ODgucG5n/original/IYYPby.png
